### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by Valiantiam** [jediefe/esintel#1]
Hey!

I'm exploring your plugin and I'm finding that any tab/page except the "Search character", results in an immediate "Whoops, looks like something went wrong."

Not sure if there is something I can help debug to assist

**Comment by Valiantiam** [comment]
![image](https://user-images.githubusercontent.com/5394853/85595871-d9514200-b60e-11ea-8bdf-efec33daa941.png)

**Comment by jediefe** [comment]
Hi, 

first of all: this plugin is quite in a rogue state and I expect it to have multiple bugs as it is fitted to a very small user scope, meaning that it fulfills mostly requirements for my alliance, which are not that common within the Eve community. 

However, I’m amazed that someone is exploring it though. 

Regarding the occured error, it seems that you’re missing a Yajra Datatable class. It’s possible that the dependencies in the composer file are not up-to-date yet. Please make sure that you’ve installed the following modules via `composer`: 

- `yajra/laravel-datatables-buttons`
- `yajra/laravel-datatables-html`
- `yajra/laravel-datatables-oracle`
